version: '2'
services:
 jar:
  build:
   context: .
   dockerfile: jar.Dockerfile
  volumes:
      - /home/student/dockerpop/pipeline/workspace/job1/docker-2/build/libs/:/opt/
  ports: 
      - 172.17.0.2:8080:8080
